# Generated by Django 4.1.13 on 2024-01-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('resume', models.FileField(upload_to='files/resume/')),
                ('image', models.ImageField(upload_to='images/profile/')),
            ],
        ),
    ]
