# Generated by Django 4.1.13 on 2024-02-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
